import { describe, it, expect } from 'vitest';
import { compileRules, detect } from '../src/detector';
import { detectLanguage } from '../src/languages';
import { extractComments } from '../src/parser';
import type { DetectorConfig } from '../src/config';

function scoreOf(comment: string, file = 'a.ts', config: DetectorConfig = {}) {
  const spec = detectLanguage(file)!;
  const [span] = extractComments(comment, spec);
  return detect(span, spec, compileRules(config));
}

describe('detector', () => {
  it('flags conversational AI openers', () => {
    expect(scoreOf('// Certainly! Here is the implementation').score).toBeGreaterThanOrEqual(45);
  });

  it('flags verbose explanations', () => {
    expect(
      scoreOf('// This is because the function allows us to keep in mind the edge case').score,
    ).toBeGreaterThanOrEqual(45);
  });

  it('leaves terse human comments alone', () => {
    expect(scoreOf('// retry twice on flaky network').score).toBeLessThan(45);
  });

  it('protects TODOs', () => {
    const result = scoreOf('// TODO: fix the race condition here');
    expect(result.protected).toBe(true);
  });

  it('protects lint directives', () => {
    expect(scoreOf('// eslint-disable-next-line no-console').protected).toBe(true);
    expect(scoreOf('# noqa: E501', 'a.py').protected).toBe(true);
  });

  it('respects a custom threshold', () => {
    const comment = '// returns the value';
    expect(scoreOf(comment, 'a.ts', { threshold: 90 }).score).toBeLessThan(90);
  });

  it('supports custom rules', () => {
    const result = scoreOf('// generated by my scaffolding', 'a.ts', {
      rules: [{ name: 'mine', pattern: 'scaffolding', weight: 50 }],
    });
    expect(result.matches).toContain('mine');
  });

  it('does not crash on invalid custom regex', () => {
    expect(() =>
      scoreOf('// hi', 'a.ts', { rules: [{ pattern: '(', weight: 50 }] }),
    ).not.toThrow();
  });

  it('honors disabled rules', () => {
    const withRule = scoreOf('// Certainly').score;
    const disabled = scoreOf('// Certainly', 'a.ts', {
      disabledRules: ['conversational-opener'],
    }).score;
    expect(disabled).toBeLessThan(withRule);
  });
});