import { normalizeCommentBody } from './parser';
import type { CommentSpan } from './types';
import type { LanguageSpec } from './languages';
import type { DetectorConfig, RuleConfig } from './config';

export interface RuleMatch {
  rule: string;
  weight: number;
}

export interface DetectResult {
  score: number;
  matches: string[];
  protected: boolean;
}

interface CompiledRule {
  name: string;
  weight: number;
  test: (body: string) => boolean;
}

/** Structural rules that operate on the comment body as a whole. */
function structuralRules(): CompiledRule[] {
  return [
    {
      name: 'conversational-opener',
      weight: 55,
      test: (b) =>
        /^(certainly|sure|of course|here('s| is)|here is|below is|the following|let me|i('ll| will)|we('ll| will)|as an ai|as a language model|note that|it('s| is) worth noting|please note|in this (example|code|function|section)|this (example|code|function|snippet) (shows|demonstrates)|hope this helps|feel free|you can (also|now)|to (do|accomplish) this|the code (above|below)|simply|first,? we|next,? we|then,? we|finally,? we)\b/i.test(
          b,
        ),
    },
    {
      name: 'verbose-explanation',
      weight: 50,
      test: (b) =>
        /\b(as (mentioned|described|explained|shown) (above|below|earlier)|this is because|which (means|allows|ensures|helps)|in order to|is (used|responsible) (to|for)|allows (us|you) to|makes (it|the code) (easier|possible)|provides a way to|note that you (should|can|must)|remember (to|that)|keep in mind|don't forget|make sure (to|that)|be careful)\b/i.test(
          b,
        ),
    },
    {
      name: 'step-narration',
      weight: 18,
      test: (b) =>
        /(^|\n)\s*(step\s*\d+|\d+[.)]\s|[*-]\s*(first|then|next|finally|after that|lastly)\b)/i.test(
          b,
        ),
    },
    {
      name: 'redundant-obvious',
      weight: 48,
      test: (b) =>
        /^(this (function|method|class|variable|constant|file|module|code|line|block|loop|component)|the (function|method|class|variable|following)|function (to|that)|method (to|that)|returns? the|sets? the|gets? the (value|result)|initialize[s]? (the|a)?|declare[s]? (the|a)?|import[s]? the|export[s]? the|define[s]? (the|a)?|create[s]? (the|a)?|called when|main function|entry point)\b/i.test(
          b,
        ),
    },
    {
      name: 'ai-disclaimer',
      weight: 40,
      test: (b) =>
        /\b(as an ai|as a language model|i am an ai|i'm an ai|generated by (an? )?(ai|chatgpt|copilot|claude|gpt)|ai-generated|this code was (auto-?)?generated|written by (chatgpt|copilot|claude|an ai))\b/i.test(
          b,
        ),
    },
    {
      name: 'emoji-decoration',
      weight: 14,
      test: (b) => /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(b),
    },
    {
      name: 'excessive-punctuation',
      weight: 8,
      test: (b) => /(!!!|\?\?\?|\.\.\.$|—\s|–\s)/.test(b) && b.length > 0,
    },
  ];
}

/** Weak signal: an unusually long prose comment. */
function lengthRule(config: DetectorConfig): CompiledRule {
  const maxWords = config.maxProseWords ?? 40;
  return {
    name: 'overly-long-prose',
    weight: 14,
    test: (b) => countWords(b) > maxWords,
  };
}

const DEFAULT_PROTECT = [
  'TODO',
  'FIXME',
  'HACK',
  'XXX',
  'NOTE:',
  'WARNING',
  'eslint-',
  'prettier-',
  'tslint:',
  'ts-ignore',
  'ts-expect-error',
  'istanbul ignore',
  'nolint',
  'noqa',
  'type: ignore',
  'pylint:',
  'mypy:',
  'go:build',
  'go:generate',
  'region',
  'endregion',
  'phpcs:',
  'coverage',
  'LICENSE',
  'Copyright',
  'SPDX-License-Identifier',
  '@license',
  '@preserve',
  '@ts-',
  '@param',
  '@returns?',
  '@throws',
  '@deprecated',
  '@see',
  '@example',
  '@author',
  '@packageDocumentation',
  'shebang',
];

export function compileRules(config: DetectorConfig): {
  rules: CompiledRule[];
  protect: RegExp[];
  threshold: number;
} {
  const custom: CompiledRule[] = (config.rules ?? [])
    .filter((r: RuleConfig) => r.enabled !== false)
    .map((r: RuleConfig) => ({
      name: r.name ?? 'custom-rule',
      weight: r.weight ?? 20,
      test: (body: string) => new RegExp(r.pattern, r.flags ?? 'i').test(body),
    }));

  const base: CompiledRule[] = [];
  const disabled = new Set((config.disabledRules ?? []).map((r) => r.toLowerCase()));
  for (const rule of [...structuralRules(), lengthRule(config)]) {
    if (!disabled.has(rule.name)) base.push(rule);
  }

  const protectPatterns = (config.protectPatterns ?? []).concat(DEFAULT_PROTECT);
  const protect = protectPatterns.map((p) => new RegExp(escapeRegExp(p), 'i'));

  return { rules: [...base, ...custom], protect, threshold: config.threshold ?? 45 };
}

export function detect(
  span: CommentSpan,
  spec: LanguageSpec,
  compiled: ReturnType<typeof compileRules>,
): DetectResult {
  const body = normalizeCommentBody(span, spec);
  const matches: RuleMatch[] = [];

  if (body.length === 0) {
    return { score: 0, matches: [], protected: false };
  }

  for (const rule of compiled.rules) {
    try {
      if (rule.test(body)) matches.push({ rule: rule.name, weight: rule.weight });
    } catch {
      // A malformed custom regex must never crash a scan.
    }
  }

  // Trivial docstrings (e.g. `"""Module."""`) carry no information and are a
  // strong tell of auto-generated documentation.
  if (
    span.kind === 'docstring' &&
    countWords(body) <= 8 &&
    /^(module|package|file|main|entry point|utility|helper|this|the)\b/i.test(body)
  ) {
    matches.push({ rule: 'trivial-docstring', weight: 50 });
  }

  const score = Math.min(100, matches.reduce((sum, m) => sum + m.weight, 0));
  const protectedComment = compiled.protect.some((re) => re.test(body));

  return { score, matches: matches.map((m) => m.rule), protected: protectedComment };
}

function countWords(text: string): number {
  const m = text.match(/[A-Za-z][A-Za-z'-]*/g);
  return m ? m.length : 0;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export { normalizeCommentBody };